// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdv1ytHr_0mo3iIhXL0rB9l7A7SsJkAuE',
    appId: '1:535514134209:web:7f80312208970722380640',
    messagingSenderId: '535514134209',
    projectId: 'ecommerce-0101',
    authDomain: 'ecommerce-0101.firebaseapp.com',
    storageBucket: 'ecommerce-0101.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4CKRsrx_wTd_1AIa_gmnhCowOFmxy_XA',
    appId: '1:535514134209:android:63ee982309a2d398380640',
    messagingSenderId: '535514134209',
    projectId: 'ecommerce-0101',
    storageBucket: 'ecommerce-0101.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYLq8ToWlu7URSYwzUPoI02U4Ysg-u-Y8',
    appId: '1:535514134209:ios:0676680aadaf19ef380640',
    messagingSenderId: '535514134209',
    projectId: 'ecommerce-0101',
    storageBucket: 'ecommerce-0101.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYLq8ToWlu7URSYwzUPoI02U4Ysg-u-Y8',
    appId: '1:535514134209:ios:0676680aadaf19ef380640',
    messagingSenderId: '535514134209',
    projectId: 'ecommerce-0101',
    storageBucket: 'ecommerce-0101.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdv1ytHr_0mo3iIhXL0rB9l7A7SsJkAuE',
    appId: '1:535514134209:web:7ccdbc16465809b6380640',
    messagingSenderId: '535514134209',
    projectId: 'ecommerce-0101',
    authDomain: 'ecommerce-0101.firebaseapp.com',
    storageBucket: 'ecommerce-0101.appspot.com',
  );
}
